services:
  - name: nuxt
    type: web
    runtime: node
    repo: https://github.com/woak973/JPTube.git
    envVars:
    - key: BACKEND_URL
      value: https://{PROJECT_NAME}.onrender.com
    buildCommand: |
      npm install
      npm run dev
    startCommand: node .output/server/index.mjs

  - name: deno
    type: web
    runtime: docker
    image:
      url: hub.docker.com/r/denoland/deno
    envVars:
    - key: BACKEND_URL
      value: https://{PROJECT_NAME}.onrender.com
    dockerCommand: deno run --allow-net --allow-read deno.ts