services:
  - name: nuxt
    type: web
    env:
      - key: BASE_URL
        value: https://{PROJECT_NAME}.onrender.com
    build:
      command: |
        git clone https://github.com/woak973/JPTube.git .
        cd your-nuxt-repo
        npm install
        npm run dev
    envFrom:
      - file: .env.production
    sourceDir: .  # ビルド後のディレクトリを指定
    startCommand: node .output/server/index.mjs

  - name: deno
    type: web
    image: denoland/deno:latest
    env:
      - key: BASE_URL
        value: https://{PROJECT_NAME}.onrender.com
    build:
      command: |
        git clone https://github.com/woak973/JPTube-Server.git .
        cd your-deno-repo
        # Denoのビルドコマンド
    envFrom:
      - file: .env.production
    sourceDir: .  # ビルド後のディレクトリを指定
    startCommand: deno run --allow-net --allow-read deno.ts