services:
  - name: jptube
    type: web
    runtime: node
    repo: https://github.com/woak973/JPTube.git
    plan: free
    buildCommand: "npm install && npm run dev"
    startCommand: "node .output/server/index.mjs"
    

  - name: jptube-server
    type: web
    runtime: docker
    repo: https://github.com/woak973/JPTube-Server.git
    plan: free
