services:
  - name: jptube
    type: web
    runtime: node
    repo: https://github.com/woak973/JPTube.git
    buildCommand: |
      npm install
      npm run dev
    startCommand: node .output/server/index.mjs

