services:
  - name: nuxt
    type: web
    runtime: node
    repo: https://github.com/woak973/JPTube.git
    env:
      BACKEND_URL: https://{PROJECT_NAME}.onrender.com
    buildCommand: |
      npm install
      npm run dev
    startCommand: node .output/server/index.mjs

  - name: deno
    type: web
    runtime: docker
    repo: https://github.com/woak973/JPTube-Server.git
    image: denoland/deno:latest
    env:
      BACKEND_URL: https://{PROJECT_NAME}.onrender.com
    startCommand: deno run --allow-net --allow-read deno.ts